name: MusicStream CI/CD

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:

  build-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./musicBackend/backend

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test (Maven)
      run: mvn clean verify

 
  build-frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./musicStream/music-stream

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: musicStream/music-stream/package-lock.json

    - name: Install Dependencies
      run: npm ci

    - name: Run Tests (Headless)
      run: npm test -- --no-watch --no-progress --browsers=ChromeHeadless

    - name: Build Production
      run: npm run build -- --configuration=production